import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import { cookies } from "next/headers";
import Darkmode from "./darkmode";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  // 서버컴포넌트에서는 쿠키를 읽거나 set할 수 있다.
  const mode = cookies().get("theme")?.value || "light";
  return (
    <html lang="en">
      <body className={mode}>
        <div>
          <div className="navbar">
            <Link href="/" className="logo">
              Appleforum
            </Link>
            <Link href="/list">List</Link>
            {session ? (
              <>
                {session?.user?.name}
                <LogoutBtn />
              </>
            ) : (
              <LoginBtn />
            )}
            <Darkmode mode={mode} />
          </div>
          <div>
            <Link href={"/join"}>회원가입</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
